
package br.gov.capes.financeiro.servico.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Classe Java de codigoErro.
 * 
 * <p>O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
 * <p>
 * <pre>
 * &lt;simpleType name="codigoErro">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ERRO_VALIDACAO"/>
 *     &lt;enumeration value="INTERNO_FINANCEIRO"/>
 *     &lt;enumeration value="IDENTIFICADOR_JA_ENCAMINHADO"/>
 *     &lt;enumeration value="ITEM_ORCAMENTARIO_REPETIDO"/>
 *     &lt;enumeration value="CONTA_NAO_ABERTA"/>
 *     &lt;enumeration value="SLR_NAO_POPULADA"/>
 *     &lt;enumeration value="DUPLICIDADE_PAGAMENTO"/>
 *     &lt;enumeration value="CONTA_JA_CRIADA"/>
 *     &lt;enumeration value="MOEDA_NAO_ENCONTRADA_SLR"/>
 *     &lt;enumeration value="NATUREZA_DESPEZA_NAO_ENCONTRADA_SLR"/>
 *     &lt;enumeration value="CARTAO_JA_CRIADO"/>
 *     &lt;enumeration value="NATUREZA_DESPESA_INVALIDA"/>
 *     &lt;enumeration value="PAGAMENTO_JA_SOLICITADO"/>
 *     &lt;enumeration value="CARTAO_PESQUISADOR_INATIVO"/>
 *     &lt;enumeration value="CARTAO_NAO_CRIADO"/>
 *     &lt;enumeration value="EMPENHO_SEM_SALDO_DISPONIVEL"/>
 *     &lt;enumeration value="EMPENHO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="PROCEDIMENTO_FINANCEIRO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="PROGRAMA_CAPES_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="SLR_INCOMPATIVEL_SERVICO"/>
 *     &lt;enumeration value="SLR_NAO_PERTENCE_SISTEMA_SOLICITANTE"/>
 *     &lt;enumeration value="SLR_NAO_ENCONTRADA"/>
 *     &lt;enumeration value="MUNICIPIO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="CARTAO_JA_SOLICITADO"/>
 *     &lt;enumeration value="CARTAO_PARA_CARGA_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="ACOMPANHAR_JA_EXECUTADO"/>
 *     &lt;enumeration value="CARTAO_PARA_ALTERACAO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="TETO_INSS_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="ACOMPANHAMENTO_SLR_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="INCONSISTENCIA_ACOMPANHAMENTO"/>
 *     &lt;enumeration value="CODIGO_OCUPACAO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="SLR_POSSUI_ULTIMO_ENCAMINHAMENTO_INCOMPATIVEL"/>
 *     &lt;enumeration value="REQUISICAO_MAL_FORMATADA"/>
 *     &lt;enumeration value="SLR_PERMITE_APENAS_UM_CREDOR"/>
 *     &lt;enumeration value="CARTAO_PARA_CANCELAMENTO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="SOLICITACAO_CARTA_ENTREGA_DESTINO_DIFERENTE"/>
 *     &lt;enumeration value="PAGAMENTO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="VARIOS_PAGAMENTOS_ENCONTRADOS"/>
 *     &lt;enumeration value="CARTAO_PESQUISADOR_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="CARTAO_EXTERIOR_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="SLR_PAGAMENTO_UNICO"/>
 *     &lt;enumeration value="SLR_SEM_SITUACAO_PAGAMENTO"/>
 *     &lt;enumeration value="EMPENHO_PARA_ANULACAO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="VARIOS_EMPENHOS_PARA_ANULACAO_ENCONTRADOS"/>
 *     &lt;enumeration value="TIPO_DESPESA_SLR_INVALIDA_PARA_ANULACAO"/>
 *     &lt;enumeration value="NATUREZA_DESPESA_SLR_ANULACAO_DIFERENTE_NATUREZA_DESPESA_SLR_ORIGINAL"/>
 *     &lt;enumeration value="VALOR_EMPENHO_ORIGINAL_DIFERENTE_EMPENHO_INFORMADO"/>
 *     &lt;enumeration value="CREDOR_ORIGINAL_DIFERENTE_CREDOR_INFORMADO"/>
 *     &lt;enumeration value="EXISTE_PAGAMENTO_FORCADO_CADASTRADO"/>
 *     &lt;enumeration value="PAGAMENTO_EFETUADO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="EXISTE_SOLICITACAO_CONSULTA_RESTRICAO"/>
 *     &lt;enumeration value="ID_CREDOR_DE_REPROCESSAMENTO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_COM_PROBLEMA"/>
 *     &lt;enumeration value="UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_GERAR_HASH_ARQUIVO"/>
 *     &lt;enumeration value="UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_DECODIFICAR_ARQUIVO"/>
 *     &lt;enumeration value="SLR_NAO_PROCESSADA"/>
 *     &lt;enumeration value="PAGAMENTO_NAO_ENCONTRADO_SHIFT"/>
 *     &lt;enumeration value="VARIOS_PAGAMENTOS_ENCONTRADOS_SHIF"/>
 *     &lt;enumeration value="SHIFT_NAO_PERMITIDO_PARA_TRAS"/>
 *     &lt;enumeration value="ATUALIZAR_REGISTROS_RESTRICOES_PAGAMENTOS_AUXPE"/>
 *     &lt;enumeration value="DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_COM_PROBLEMA"/>
 *     &lt;enumeration value="DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_DECODIFICAR_ARQUIVO"/>
 *     &lt;enumeration value="DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ARQUIVO_NAO_ENCONTRADO"/>
 *     &lt;enumeration value="DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_INFO_ARQUIVO_NAO_ENCONTRADA"/>
 *     &lt;enumeration value="CEP_NAO_INFORMADO"/>
 *     &lt;enumeration value="CEP_ZERADO_NAO_ACEITO"/>
 *     &lt;enumeration value="EXISTE_SOLICITACAO_CONSULTA_RESTRICAO_PESQUISADOR"/>
 *     &lt;enumeration value="VALOR_PAGAMENTO_ZERADO_NAO_ACEITO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "codigoErro")
@XmlEnum
public enum CodigoErro {

    ERRO_VALIDACAO,
    INTERNO_FINANCEIRO,
    IDENTIFICADOR_JA_ENCAMINHADO,
    ITEM_ORCAMENTARIO_REPETIDO,
    CONTA_NAO_ABERTA,
    SLR_NAO_POPULADA,
    DUPLICIDADE_PAGAMENTO,
    CONTA_JA_CRIADA,
    MOEDA_NAO_ENCONTRADA_SLR,
    NATUREZA_DESPEZA_NAO_ENCONTRADA_SLR,
    CARTAO_JA_CRIADO,
    NATUREZA_DESPESA_INVALIDA,
    PAGAMENTO_JA_SOLICITADO,
    CARTAO_PESQUISADOR_INATIVO,
    CARTAO_NAO_CRIADO,
    EMPENHO_SEM_SALDO_DISPONIVEL,
    EMPENHO_NAO_ENCONTRADO,
    PROCEDIMENTO_FINANCEIRO_NAO_ENCONTRADO,
    PROGRAMA_CAPES_NAO_ENCONTRADO,
    SLR_INCOMPATIVEL_SERVICO,
    SLR_NAO_PERTENCE_SISTEMA_SOLICITANTE,
    SLR_NAO_ENCONTRADA,
    MUNICIPIO_NAO_ENCONTRADO,
    CARTAO_JA_SOLICITADO,
    CARTAO_PARA_CARGA_NAO_ENCONTRADO,
    ACOMPANHAR_JA_EXECUTADO,
    CARTAO_PARA_ALTERACAO_NAO_ENCONTRADO,
    TETO_INSS_NAO_ENCONTRADO,
    ACOMPANHAMENTO_SLR_NAO_ENCONTRADO,
    INCONSISTENCIA_ACOMPANHAMENTO,
    CODIGO_OCUPACAO_NAO_ENCONTRADO,
    SLR_POSSUI_ULTIMO_ENCAMINHAMENTO_INCOMPATIVEL,
    REQUISICAO_MAL_FORMATADA,
    SLR_PERMITE_APENAS_UM_CREDOR,
    CARTAO_PARA_CANCELAMENTO_NAO_ENCONTRADO,
    SOLICITACAO_CARTA_ENTREGA_DESTINO_DIFERENTE,
    PAGAMENTO_NAO_ENCONTRADO,
    VARIOS_PAGAMENTOS_ENCONTRADOS,
    CARTAO_PESQUISADOR_NAO_ENCONTRADO,
    CARTAO_EXTERIOR_NAO_ENCONTRADO,
    SLR_PAGAMENTO_UNICO,
    SLR_SEM_SITUACAO_PAGAMENTO,
    EMPENHO_PARA_ANULACAO_NAO_ENCONTRADO,
    VARIOS_EMPENHOS_PARA_ANULACAO_ENCONTRADOS,
    TIPO_DESPESA_SLR_INVALIDA_PARA_ANULACAO,
    NATUREZA_DESPESA_SLR_ANULACAO_DIFERENTE_NATUREZA_DESPESA_SLR_ORIGINAL,
    VALOR_EMPENHO_ORIGINAL_DIFERENTE_EMPENHO_INFORMADO,
    CREDOR_ORIGINAL_DIFERENTE_CREDOR_INFORMADO,
    EXISTE_PAGAMENTO_FORCADO_CADASTRADO,
    PAGAMENTO_EFETUADO_NAO_ENCONTRADO,
    EXISTE_SOLICITACAO_CONSULTA_RESTRICAO,
    ID_CREDOR_DE_REPROCESSAMENTO_NAO_ENCONTRADO,
    UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_COM_PROBLEMA,
    UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_GERAR_HASH_ARQUIVO,
    UPLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_DECODIFICAR_ARQUIVO,
    SLR_NAO_PROCESSADA,
    PAGAMENTO_NAO_ENCONTRADO_SHIFT,
    VARIOS_PAGAMENTOS_ENCONTRADOS_SHIF,
    SHIFT_NAO_PERMITIDO_PARA_TRAS,
    ATUALIZAR_REGISTROS_RESTRICOES_PAGAMENTOS_AUXPE,
    DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_COM_PROBLEMA,
    DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ERRO_DECODIFICAR_ARQUIVO,
    DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_ARQUIVO_NAO_ENCONTRADO,
    DOWNLOAD_DOCUMENTO_PAGAMENTO_DEVOLVIDO_INFO_ARQUIVO_NAO_ENCONTRADA,
    CEP_NAO_INFORMADO,
    CEP_ZERADO_NAO_ACEITO,
    EXISTE_SOLICITACAO_CONSULTA_RESTRICAO_PESQUISADOR,
    VALOR_PAGAMENTO_ZERADO_NAO_ACEITO;

    public String value() {
        return name();
    }

    public static CodigoErro fromValue(String v) {
        return valueOf(v);
    }

}
